### ISSUE TITLE
Dependent dropdowns problem

### ISSUE THREAD

**Issue by mjpramos** [Lutrasoft/Fancyform#11]
Hi, 
I'm using facyform on an app I'm building.
On the main page I have 2 dependent dropdowns. The 1st selectbox is filled on page load and the plugin works, but since the 2nd selectbox is only populated after selecting an option from the 1st, it doesn't get transformed.
I tried calling the transformSelect method on the change event of the 1st but with no success.
Is there anything I'm missing?

Thanks

**Comment by tsukasa1989** [comment]
Hello,

If you have initialized the transformSelect, you can not initialize it again. If you change te values of the SELECT you need a repaint

```javascript
$( "select" ).transformSelect( "repaint" );
```

Good luck.

**Comment by mjpramos** [comment]
Hi tsukasa! 
That worked like a charm! Thank you so much.
